# Generated by Django 2.2.6 on 2019-10-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('poll_jsonstring', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
